baseurl = "https://kclreflect.gitlab.io"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = ""
canonifyurls  = true
enableEmoji = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = ""
  logo = ""
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
  custom_css = ["css/style.css"]
  lastchange=2022

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Martin Chapman"
  gitlab = "kclreflect"
  twitter = "martin_chap_man"


[[menu.main]]
    name = "about"
    url = "#about"
    weight = 1

[[menu.main]]
    name = "partners"
    url = "#partners"
    weight = 1

[[menu.main]]
    name = "people"
    url = "#people"
    weight = 1

[[menu.main]]
    identifier = "software"
    name = "software"
    url = "#software"
    weight = 2

[[menu.main]]
    parent = "software"
    name = "architecture"
    url = "#architecture"
    weight = 1

[[menu.main]]
    parent = "software"
    name = "stack"
    url = "#stack"
    weight = 1

[[menu.main]]
    parent = "software"
    name = "flow"
    url = "#flow"
    weight = 1
